name: WPF .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build -c Release
      
    - uses: actions/upload-artifact@v2
      with:
          name: nupkg
          path: bin/Release/*.nupkg
      
    - uses: actions/upload-artifact@v2
      with:
          name: Example net45
          path: ExampleApp/bin/Release/net45
      
    - uses: actions/upload-artifact@v2
      with:
          name: Example net5.0
          path: ExampleApp/bin/Release/net5.0-windows
