name: Build .NET WPF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1

    - name: Build
      run: |
        dotnet --info
        dotnet build -c Release
      
    - uses: actions/upload-artifact@v2
      with:
          name: WpfEnumMenuItem
          path: WpfEnumMenuItem/bin/Release/
      
    - uses: actions/upload-artifact@v2
      with:
          name: ExampleApp
          path: ExampleApp/bin/Release/
